export const rows = [
  {
    id: 1,
    firstName: 'Tobie',
    lastName: 'Beauly',
    email: 'tbeauly0@cmu.edu',
    telephone: '+976 884 706 1071',
    poste: 'Help Desk Technician',
    salaire: '1639,53€',
  },
  {
    id: 2,
    firstName: 'Enid',
    lastName: 'Lauritsen',
    email: 'elauritsen1@chicagotribune.com',
    telephone: '+86 452 464 6926',
    poste: 'Programmer Analyst II',
    salaire: '1919,52€',
  },
  {
    id: 3,
    firstName: 'Bart',
    lastName: 'Mullaney',
    email: 'bmullaney2@psu.edu',
    telephone: '+86 956 972 6150',
    poste: 'Graphic Designer',
    salaire: '2836,79€',
  },
  {
    id: 4,
    firstName: 'Mia',
    lastName: 'Thresher',
    email: 'mthresher3@ox.ac.uk',
    telephone: '+60 912 948 2504',
    poste: 'Research Assistant III',
    salaire: '2738,10€',
  },
  {
    id: 5,
    firstName: 'Gauthier',
    lastName: 'Callery',
    email: 'gcallery4@fema.gov',
    telephone: '+62 338 249 7518',
    poste: 'Chemical Engineer',
    salaire: '2921,34€',
  },
  {
    id: 6,
    firstName: 'Katuscha',
    lastName: 'Steabler',
    email: 'ksteabler5@gravatar.com',
    telephone: '+64 101 705 0670',
    poste: 'Systems Administrator I',
    salaire: '1849,99€',
  },
  {
    id: 7,
    firstName: 'Dorie',
    lastName: 'Blunderfield',
    email: 'dblunderfield6@youtu.be',
    telephone: '+63 742 641 5076',
    poste: 'Nurse',
    salaire: '1795,58€',
  },
  {
    id: 8,
    firstName: 'Othilie',
    lastName: 'Dearnaley',
    email: 'odearnaley7@cmu.edu',
    telephone: '+420 965 526 2583',
    poste: 'Cost Accountant',
    salaire: '2437,91€',
  },
  {
    id: 9,
    firstName: 'Eleni',
    lastName: 'Commins',
    email: 'ecommins8@google.it',
    telephone: '+86 111 370 2128',
    poste: 'Financial Advisor',
    salaire: '1866,15€',
  },
  {
    id: 10,
    firstName: 'Lina',
    lastName: 'Dellenbrook',
    email: 'ldellenbrook9@quantcast.com',
    telephone: '+420 311 693 0216',
    poste: 'Software Consultant',
    salaire: '2621,52€',
  },
];
